name: stock_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4
  syncfusion_flutter_charts: ^28.2.9
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  web_socket_channel: ^2.4.0
  intl: ^0.20.2
  dio: ^5.4.1
  uuid: ^4.3.3
  google_sign_in: ^6.3.0
  file_picker: ^9.2.1
  path: ^1.9.0
  go_router: ^14.8.1
  fl_chart: ^0.70.2
  flutter_pdfview: ^1.4.0
  image_picker: ^1.0.7
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
  assets:
    - config.env
    - assets/images/background.png
    - assets/icons/auth.png
    - assets/images/top_logo.png
    - assets/images/alternate_top_logo.png
    - assets/icons/google.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
